### ISSUE TITLE
The models are different in paper, code and trained models

### ISSUE THREAD

**Issue by 5663015** [jiefengpeng/DNA#4]
I mainly focus on DNA-c model, but I found the model structure in the paper, architecture defined  in code, and the released trained model are all different. Which model is the best? Could you provide a definite network structure? Thank you!

**Comment by wanggrun** [comment]
> I mainly focus on DNA-c model, but I found the model structure in the paper, architecture defined in code, and the released trained model are all different. Which model is the best? Could you provide a definite network structure? Thank you!


Thank you for the careful reading. The published code (i.e., the architecture) matches the released weights. However, the architecture is not the one we mentioned in the paper due to our carelessness -- we uploaded a different model by accident. 


Actually, our method has found a series of architectures with similar model size and performance, i.e., the model we previously uploaded and the model we mentioned in the paper share the same parameter size and accuracy. 


Now, the mistake has been corrected. You can download the new DNA_c.pth.tar and update the model.py for validation.

**Comment by 5663015** [comment]
Thank you very much!
