### ISSUE TITLE
Do you use Catout in training and transfer learning process?

### ISSUE THREAD

**Issue by 5663015** [jiefengpeng/DNA#6]
Could you show us the details of data augmentation? I have some trouble recurring transfer learning and DNA_c, thank you very much !

**Comment by jiefengpeng** [comment]
We disabled cutout in Imagenet training and enabled it in transfer learning. We use AutoAugment for data augmentation when we train Imagenet. More details can be found in:
Cubuk, E. D., Zoph, B., Mane, D., Vasudevan, V., and Le, Q. V. Autoaugment: Learning augmentation policies from data. CVPR, 2019. And there are some tips in transfer learning. https://github.com/jiefengpeng/DNA/issues/3#issuecomment-564472641

**Comment by 5663015** [comment]
AutoAugment is also enabled in transfer learning? @jiefengpeng

**Comment by jiefengpeng** [comment]
Not yet, we use regular augmentation like normalize, random crop, resize, horizontal flip and colorjitter since the transfer dataset is simple. But it may help using AA in transfer learning. One more thing, make sure that the mean and std in normalization are:
IMAGENET_DEFAULT_MEAN = (0.485, 0.456, 0.406)
IMAGENET_DEFAULT_STD = (0.229, 0.224, 0.225)
